version: '3.8'

services:
  # grpc:
  #   image: neurodyne8nws/caddy-grpc
  #   container_name: grpc
  #   build:
  #     dockerfile: Dockerfile.caddy
  #     context: .

  back:
    image: neurodyne8nws/caddy-back
    container_name: back
    ports:
      - 50051:50051

  caddy:
    image: neurodyne8nws/caddy-grpc
    container_name: caddy
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    expose:
      - 50051
    ports:
      - 2019:2019
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./dist:/app/dist
